apiVersion: v1
kind: Service
metadata:
  name: helloworld-flask-service
spec:
  type: NodePort
  selector:
    app: helloworld-flask
  ports:
    - protocol: TCP
      port: 32777
      targetPort: 32777